name: dio_retry_plus
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/SunnatilloShavkatov/dio_retry_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: any
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter: