name: dio_retry_plus
description: A plugin for dio that retries failed requests.
version: 2.0.6
homepage: https://github.com/SunnatilloShavkatov/dio_retry_plus

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
