name: dio_retry_plus
description: A plugin for dio that retries failed requests.
version: 2.0.0
homepage: https://github.com/SunnatilloShavkatov/dio_retry_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter: