name: dio_retry_plus
description: A plugin for dio that retries failed requests.
version: 2.0.7
homepage: https://github.com/SunnatilloShavkatov/dio_retry_plus

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
